### ISSUE TITLE
Awesome list! 

### ISSUE THREAD

**Issue by Overtorment** [alexk111/awesome-bitcoin-payment-processors#1]
I maintaing pretty old btc payment processor here https://github.com/Overtorment/Cashier-BTC and also theres a list of payment processors (see bottom of readme).
Do you mind if Ill port this whole list to this repo..?

**Comment by shivaenigma** [comment]
Followed here from #DeBitpay. Looking good ! Any reason to not include Blockonomics ? We also wrote a blog post recently detailing about the [alternatives](https://blog.blockonomics.co/top-5-bitpay-alternatives-46df15ea0c31)

**Comment by alexk111** [comment]
@shivaenigma Included, thanks!

**Comment by alexk111** [comment]
@Overtorment I've ported the list. Skipped Electrum's solution which is about setting up a server accepting Bitcoin via BIP70 payment protocol.

**Comment by shivaenigma** [comment]
Thanks a lot, I would also request the below in merchant stories 
https://www.youtube.com/watch?v=fPyL6y-iv54

Regards and Thanks

**Comment by alexk111** [comment]
@shivaenigma I've found a text version on hackernoon and added it to the stories.

**Comment by Overtorment** [comment]
@alexk111 

1) I would still add electrum, as it is an opensource way to accept btc

2) some items on my list were stricken out - this is how I marked processors that supported malicious hardfork

**Comment by alexk111** [comment]
@Overtorment 

> I would still add electrum

No, sorry. Zero tolerance to BIP-70.

> some items on my list were stricken out - this is how I marked processors that supported malicious hardfork

Thanks for pointing at this. Removed coinbase. Also found that they practice financial censorship.
